-- EXEC CREATE_MASTER_TABLES
-- EXEC CREATE_TRANSACTIONAL_TABLES

DROP TABLE incidente_por_auto;
DROP TABLE incidente;
DROP TABLE telemetria_neumatico;
DROP TABLE telemetria_freno;
DROP TABLE telemetria_motor;
DROP TABLE telemetria_caja;
DROP TABLE telemetria_auto;
DROP TABLE parada_box_por_vehiculo;
DROP TABLE parada_box;
DROP TABLE sector;
DROP TABLE carrera;
DROP TABLE circuito;
DROP TABLE vehiculo;
DROP TABLE neumatico;
DROP TABLE freno;
DROP TABLE motor;
DROP TABLE caja;
DROP TABLE bandera;
DROP TABLE pais;
DROP TABLE tipo_neumatico;
DROP TABLE tipo_sector;
DROP TABLE tipo_incidente;
DROP TABLE piloto;
DROP TABLE escuderia;