

USE [GRUPO_9800]
GO
-- Caja
CREATE PROCEDURE migrar_caja
AS
BEGIN
	INSERT INTO caja
	(caja_nro_serie, caja_modelo, caja_desgaste) 
	SELECT TELE_CAJA_NRO_SERIE, TELE_CAJA_MODELO, TELE_CAJA_DESGASTE
	FROM GD1C2022.gd_esquema.Maestra
	WHERE TELE_CAJA_NRO_SERIE IS NOT NULL
	GROUP BY TELE_CAJA_NRO_SERIE, TELE_CAJA_MODELO, TELE_CAJA_DESGASTE
END
GO

-- Motor
CREATE PROCEDURE migrar_motor 
AS
BEGIN
	INSERT INTO motor
	(motor_nro_serie, motor_modelo)
	SELECT TELE_MOTOR_NRO_SERIE, TELE_MOTOR_MODELO
	FROM GD1C2022.gd_esquema.Maestra
	WHERE TELE_MOTOR_NRO_SERIE IS NOT NULL
	GROUP BY TELE_MOTOR_NRO_SERIE, TELE_MOTOR_MODELO
END
GO

-- Freno
CREATE PROCEDURE migrar_freno 
AS
BEGIN
	INSERT INTO freno
	(freno_nro_serie, freno_tamanio_pastilla)
	select TELE_FRENO1_NRO_SERIE,TELE_FRENO1_TAMANIO_DISCO /*FRENO 1*/
	from GD1C2022.gd_esquema.Maestra
	WHERE TELE_FRENO1_NRO_SERIE IS NOT NULL
	UNION
	select TELE_FRENO2_NRO_SERIE,TELE_FRENO2_TAMANIO_DISCO /*FRENO 2*/
	from GD1C2022.gd_esquema.Maestra
	WHERE TELE_FRENO2_NRO_SERIE IS NOT NULL
	UNION
	select TELE_FRENO3_NRO_SERIE,TELE_FRENO3_TAMANIO_DISCO /*FRENO 3*/
	from GD1C2022.gd_esquema.Maestra
	WHERE TELE_FRENO3_NRO_SERIE IS NOT NULL
	UNION
	select TELE_FRENO4_NRO_SERIE,TELE_FRENO4_TAMANIO_DISCO /*FRENO 4*/
	from GD1C2022.gd_esquema.Maestra
	WHERE TELE_FRENO4_NRO_SERIE IS NOT NULL

END 

-- Tipo neumatico 
GO
CREATE PROCEDURE migrar_tipo_neumatico 
AS
BEGIN
	INSERT INTO tipo_neumatico
	(descripcion)
	select NEUMATICO1_TIPO_NUEVO /*TIPO NEUMATICO*/
	from GD1C2022.gd_esquema.Maestra
	UNION 
	select NEUMATICO2_TIPO_NUEVO /*TIPO NEUMATICO*/
	from GD1C2022.gd_esquema.Maestra
	UNION 
	select NEUMATICO3_TIPO_NUEVO /*TIPO NEUMATICO*/
	from GD1C2022.gd_esquema.Maestra
	UNION 
	select NEUMATICO4_TIPO_NUEVO /*TIPO NEUMATICO*/
	from GD1C2022.gd_esquema.Maestra
	UNION 
	select NEUMATICO1_TIPO_VIEJO/*TIPO NEUMATICO*/
	from GD1C2022.gd_esquema.Maestra
	UNION 
	select NEUMATICO2_TIPO_VIEJO /*TIPO NEUMATICO*/
	FROM GD1C2022.gd_esquema.Maestra
	UNION 
	select NEUMATICO3_TIPO_VIEJO/*TIPO NEUMATICO*/
	from GD1C2022.gd_esquema.Maestra
	UNION 
	select NEUMATICO3_TIPO_VIEJO/*TIPO NEUMATICO*/
	from GD1C2022.gd_esquema.Maestra
	group by 
	NEUMATICO1_TIPO_NUEVO,
	NEUMATICO2_TIPO_NUEVO,
	NEUMATICO3_TIPO_NUEVO,
	NEUMATICO4_TIPO_NUEVO,
	NEUMATICO1_TIPO_VIEJO,
	NEUMATICO2_TIPO_VIEJO,
	NEUMATICO3_TIPO_VIEJO,
	NEUMATICO3_TIPO_VIEJO
END
GO


-- Tipo Sector
CREATE PROCEDURE migrar_tipo_sector 
AS
BEGIN
	INSERT INTO tipo_sector
	(descripcion)
	select SECTO_TIPO /*TIPO_SECTOR*/
	from GD1C2022.gd_esquema.Maestra
	group by SECTO_TIPO
END
GO

-- Tipo incidente
CREATE PROCEDURE migrar_tipo_incidente 
AS
BEGIN
	INSERT INTO tipo_incidente
	(descripcion)
	select INCIDENTE_TIPO /*TIPO_INCIDENTE*/
	from GD1C2022.gd_esquema.Maestra
	GROUP BY INCIDENTE_TIPO
END
GO

-- Pais 
CREATE PROCEDURE migrar_pais 
AS
	BEGIN
	INSERT INTO pais
	(nombre)
	select CIRCUITO_PAIS /*PAIS*/
	from GD1C2022.gd_esquema.Maestra
	GROUP BY CIRCUITO_PAIS
END
GO


-- Bandera
CREATE PROCEDURE migrar_bandera 
AS
BEGIN
	INSERT INTO bandera
	(incidente_bandera)
	select INCIDENTE_BANDERA /*BANDERA*/
	from GD1C2022.gd_esquema.Maestra
	GROUP BY INCIDENTE_BANDERA
END
GO

-- Escuderia
CREATE PROCEDURE migrar_escuderia 
AS
BEGIN
    INSERT INTO escuderia 
	(escuderia_nombre, escuderia_nacionalidad)
    select ESCUDERIA_NOMBRE,ESCUDERIA_NACIONALIDAD
    from GD1C2022.gd_esquema.Maestra
	GROUP BY ESCUDERIA_NOMBRE,ESCUDERIA_NACIONALIDAD
END
GO

-- Piloto
CREATE PROCEDURE migrar_piloto 
AS
BEGIN
    INSERT INTO piloto 
    (piloto_nombre, piloto_apellido, piloto_nacionalidad, piloto_fecha_nacimiento)
    select PILOTO_NOMBRE, PILOTO_APELLIDO, PILOTO_NACIONALIDAD, PILOTO_FECHA_NACIMIENTO /*PILOTO*/
    from GD1C2022.gd_esquema.Maestra
	GROUP BY 
	PILOTO_NOMBRE, 
	PILOTO_APELLIDO, 
	PILOTO_NACIONALIDAD, 
	PILOTO_FECHA_NACIMIENTO
END
GO

-- Circuito
CREATE PROCEDURE migrar_circuito
AS
    BEGIN
        INSERT INTO circuito 
        (circuito_codigo,circuito_nombre,id_pais)
        SELECT CIRCUITO_CODIGO,CIRCUITO_NOMBRE,CIRCUITO_PAIS
        FROM GD1C2022.gd_esquema.maestra
		WHERE CIRCUITO_CODIGO IS NOT NULL
		GROUP BY CIRCUITO_CODIGO,CIRCUITO_NOMBRE,CIRCUITO_PAIS
    END
GO

-- Carrera
CREATE PROCEDURE migrar_carrera
AS 
BEGIN 
	INSERT INTO carrera
	(codigo_carrera,carrera_fecha,carrera_clima,carrera_cant_vueltas,circuito_codigo)
	SELECT CODIGO_CARRERA,CARRERA_FECHA,CARRERA_CLIMA,CARRERA_CANT_VUELTAS,CIRCUITO_CODIGO
	FROM GD1C2022.gd_esquema.Maestra
	WHERE CODIGO_CARRERA IS NOT NULL
	GROUP BY CODIGO_CARRERA,CARRERA_FECHA,CARRERA_CLIMA,CARRERA_CANT_VUELTAS,CIRCUITO_CODIGO
END 
GO

-- Sector
CREATE PROCEDURE migrar_sector
AS 
BEGIN 
	INSERT INTO sector
	(codigo_sector,circuito_codigo,sector_distancia,id_tipo_sector)
	SELECT CODIGO_SECTOR,CIRCUITO_CODIGO,SECTOR_DISTANCIA,id_tipo_sector
	FROM GD1C2022.gd_esquema.Maestra
	JOIN tipo_sector ON descripcion = SECTO_TIPO
	WHERE CODIGO_SECTOR IS NOT NULL
	AND CIRCUITO_CODIGO IS NOT NULL
	GROUP BY CODIGO_SECTOR,CIRCUITO_CODIGO,SECTOR_DISTANCIA,id_tipo_sector
END 
GO

-- Parada box
CREATE PROCEDURE migrar_parada_box
AS
BEGIN 
	INSERT INTO parada_box
	(parada_box_vuelta,parada_box_tiempo,codigo_carrera)
	SELECT PARADA_BOX_VUELTA,PARADA_BOX_TIEMPO,CODIGO_CARRERA
	FROM GD1C2022.gd_esquema.Maestra
	-- Ver si hay que meterle un group by.
END 

----------------------------
GO
-- Telemetria caja
CREATE PROCEDURE migrar_telemetria_caja
AS 
BEGIN
	INSERT INTO telemetria_caja
	SELECT TELE_AUTO_CODIGO,TELE_CAJA_NRO_SERIE,TELE_CAJA_TEMP_ACEITE,TELE_CAJA_RPM,TELE_CAJA_DESGASTE
	FROM GD1C2022.gd_esquema.Maestra
	WHERE TELE_AUTO_CODIGO IS NOT NULL
	AND TELE_CAJA_NRO_SERIE IS NOT NULL
END

GO
-- Telemetria motor
CREATE PROCEDURE migrar_telemetria_motor
AS 
BEGIN
	INSERT INTO telemetria_motor
	SELECT TELE_AUTO_CODIGO,TELE_MOTOR_NRO_SERIE,TELE_MOTOR_POTENCIA,
			TELE_MOTOR_TEMP_ACEITE,TELE_MOTOR_TEMP_AGUA,TELE_MOTOR_RPM
	FROM GD1C2022.gd_esquema.Maestra
	WHERE TELE_AUTO_CODIGO IS NOT NULL
	AND TELE_MOTOR_NRO_SERIE IS NOT NULL
END

GO
--Telemetria neumatico
CREATE PROCEDURE migrar_telemetria_neumatico
AS 
BEGIN
	INSERT INTO telemetria_neumatico
	select TELE_AUTO_CODIGO,TELE_NEUMATICO1_NRO_SERIE,TELE_NEUMATICO1_PROFUNDIDAD,TELE_NEUMATICO1_POSICION,	
			TELE_NEUMATICO1_PRESION, TELE_NEUMATICO1_TEMPERATURA
	from GD1C2022.gd_esquema.Maestra
	WHERE TELE_AUTO_CODIGO IS NOT NULL
	AND TELE_NEUMATICO1_NRO_SERIE IS NOT NULL
	UNION
	select TELE_AUTO_CODIGO,TELE_NEUMATICO2_NRO_SERIE,TELE_NEUMATICO2_PROFUNDIDAD,TELE_NEUMATICO2_POSICION,	
			TELE_NEUMATICO2_PRESION, TELE_NEUMATICO2_TEMPERATURA /*FRENO 2*/
	from GD1C2022.gd_esquema.Maestra
		WHERE TELE_AUTO_CODIGO IS NOT NULL
	AND TELE_NEUMATICO2_NRO_SERIE IS NOT NULL
	UNION
	select TELE_AUTO_CODIGO,TELE_NEUMATICO3_NRO_SERIE,TELE_NEUMATICO3_PROFUNDIDAD,TELE_NEUMATICO3_POSICION,	
			TELE_NEUMATICO3_PRESION, TELE_NEUMATICO3_TEMPERATURA /*FRENO 3*/
	from GD1C2022.gd_esquema.Maestra
		WHERE TELE_AUTO_CODIGO IS NOT NULL
	AND TELE_NEUMATICO3_NRO_SERIE IS NOT NULL
	UNION
	select TELE_AUTO_CODIGO,TELE_NEUMATICO4_NRO_SERIE,TELE_NEUMATICO4_PROFUNDIDAD,TELE_NEUMATICO4_POSICION,	
			TELE_NEUMATICO1_PRESION, TELE_NEUMATICO4_TEMPERATURA /*FRENO 4*/
	from GD1C2022.gd_esquema.Maestra
		WHERE TELE_AUTO_CODIGO IS NOT NULL
	AND TELE_NEUMATICO4_NRO_SERIE IS NOT NULL
END 
GO     
--Telemetria freno
CREATE PROCEDURE migrar_telemetria_freno
AS 
BEGIN
	INSERT INTO telemetria_freno
	select TELE_AUTO_CODIGO ,TELE_FRENO1_NRO_SERIE,TELE_FRENO1_GROSOR_PASTILLA,TELE_FRENO1_TAMANIO_DISCO,
			TELE_FRENO1_POSICION,TELE_FRENO1_TEMPERATURA
	FROM GD1C2022.gd_esquema.Maestra
	WHERE TELE_AUTO_CODIGO IS NOT NULL
	AND TELE_FRENO1_NRO_SERIE IS NOT NULL
	UNION
	select TELE_AUTO_CODIGO ,TELE_FRENO2_NRO_SERIE,TELE_FRENO2_GROSOR_PASTILLA,TELE_FRENO2_TAMANIO_DISCO,
			TELE_FRENO2_POSICION,TELE_FRENO2_TEMPERATURA /*FRENO 2*/
	from GD1C2022.gd_esquema.Maestra
	WHERE TELE_AUTO_CODIGO IS NOT NULL
	AND TELE_FRENO2_NRO_SERIE IS NOT NULL
	UNION
	select TELE_AUTO_CODIGO ,TELE_FRENO3_NRO_SERIE,TELE_FRENO3_GROSOR_PASTILLA,TELE_FRENO3_TAMANIO_DISCO,
			TELE_FRENO3_POSICION,TELE_FRENO3_TEMPERATURA /*FRENO 3*/
	from GD1C2022.gd_esquema.Maestra
	WHERE TELE_AUTO_CODIGO IS NOT NULL
	AND TELE_FRENO3_NRO_SERIE IS NOT NULL
	UNION
	select TELE_AUTO_CODIGO ,TELE_FRENO4_NRO_SERIE,TELE_FRENO4_GROSOR_PASTILLA,TELE_FRENO4_TAMANIO_DISCO,
			TELE_FRENO4_POSICION,TELE_FRENO4_TEMPERATURA /*FRENO 4*/
	from GD1C2022.gd_esquema.Maestra
	WHERE TELE_AUTO_CODIGO IS NOT NULL
	AND TELE_FRENO4_NRO_SERIE IS NOT NULL
	 
END


-- Revisar / Demasiadas filas.
GO
--Telemetria auto
CREATE PROCEDURE migrar_telemetria_auto
AS
BEGIN 

	INSERT INTO telemetria_auto
	(tele_auto_cod,vehiculo_numero,cod_escuderia,codigo_carrera,tele_fecha,tele_auto_numero_vuelta,codigo_sector,circuito_codigo,
	tele_auto_distancia_carrera,tele_auto_distancia_vuelta,tele_auto_tiempo_vuelta,tele_auto_posicion,
	tele_auto_combustible,caja_nro_serie,motor_nro_serie,neumatico_nro_serie,freno_nro_serie)
	SELECT TELE_AUTO_CODIGO,AUTO_NUMERO,cod_escuderia,CODIGO_CARRERA,CARRERA_FECHA,TELE_AUTO_NUMERO_VUELTA,CODIGO_SECTOR,CIRCUITO_CODIGO,
			TELE_AUTO_DISTANCIA_CARRERA,TELE_AUTO_DISTANCIA_VUELTA,TELE_AUTO_TIEMPO_VUELTA,TELE_AUTO_POSICION,
			TELE_AUTO_COMBUSTIBLE,TELE_CAJA_NRO_SERIE,TELE_MOTOR_NRO_SERIE,TELE_NEUMATICO1_NRO_SERIE,TELE_FRENO1_NRO_SERIE
	FROM GD1C2022.gd_esquema.Maestra
	JOIN escuderia e ON e.escuderia_nombre = GD1C2022.gd_esquema.Maestra.ESCUDERIA_NOMBRE 
	WHERE TELE_AUTO_CODIGO IS NOT NULL
	UNION 
	SELECT TELE_AUTO_CODIGO,AUTO_NUMERO,cod_escuderia,CODIGO_CARRERA,CARRERA_FECHA,TELE_AUTO_NUMERO_VUELTA,CODIGO_SECTOR,CIRCUITO_CODIGO,
			TELE_AUTO_DISTANCIA_CARRERA,TELE_AUTO_DISTANCIA_VUELTA,TELE_AUTO_TIEMPO_VUELTA,TELE_AUTO_POSICION,
			TELE_AUTO_COMBUSTIBLE,TELE_CAJA_NRO_SERIE,TELE_MOTOR_NRO_SERIE,TELE_NEUMATICO2_NRO_SERIE,TELE_FRENO2_NRO_SERIE
	FROM GD1C2022.gd_esquema.Maestra
	JOIN escuderia e ON e.escuderia_nombre = GD1C2022.gd_esquema.Maestra.ESCUDERIA_NOMBRE 
	WHERE TELE_AUTO_CODIGO IS NOT NULL
	UNION 
	SELECT TELE_AUTO_CODIGO,AUTO_NUMERO,cod_escuderia,CODIGO_CARRERA,CARRERA_FECHA,TELE_AUTO_NUMERO_VUELTA,CODIGO_SECTOR,CIRCUITO_CODIGO,
			TELE_AUTO_DISTANCIA_CARRERA,TELE_AUTO_DISTANCIA_VUELTA,TELE_AUTO_TIEMPO_VUELTA,TELE_AUTO_POSICION,
			TELE_AUTO_COMBUSTIBLE,TELE_CAJA_NRO_SERIE,TELE_MOTOR_NRO_SERIE,TELE_NEUMATICO3_NRO_SERIE,TELE_FRENO3_NRO_SERIE
	FROM GD1C2022.gd_esquema.Maestra
	JOIN escuderia e ON e.escuderia_nombre = GD1C2022.gd_esquema.Maestra.ESCUDERIA_NOMBRE 
	WHERE TELE_AUTO_CODIGO IS NOT NULL
	UNION 
	SELECT TELE_AUTO_CODIGO,AUTO_NUMERO,cod_escuderia,CODIGO_CARRERA,CARRERA_FECHA,TELE_AUTO_NUMERO_VUELTA,CODIGO_SECTOR,CIRCUITO_CODIGO,
			TELE_AUTO_DISTANCIA_CARRERA,TELE_AUTO_DISTANCIA_VUELTA,TELE_AUTO_TIEMPO_VUELTA,TELE_AUTO_POSICION,
			TELE_AUTO_COMBUSTIBLE,TELE_CAJA_NRO_SERIE,TELE_MOTOR_NRO_SERIE,TELE_NEUMATICO4_NRO_SERIE,TELE_FRENO4_NRO_SERIE
	FROM GD1C2022.gd_esquema.Maestra
	JOIN escuderia e ON e.escuderia_nombre = GD1C2022.gd_esquema.Maestra.ESCUDERIA_NOMBRE 
	WHERE TELE_AUTO_CODIGO IS NOT NULL

END 
GO

-- Incidente
CREATE PROCEDURE migrar_incidente
AS
    BEGIN
        INSERT INTO incidente
        (codigo_sector,circuito_codigo, codigo_carrera, tiempo_incidente,id_incidente_bandera)
        SELECT CODIGO_SECTOR,CIRCUITO_CODIGO, CODIGO_CARRERA, INCIDENTE_TIEMPO,ti.id_tipo_incidente
        FROM GD1C2022.gd_esquema.maestra
		JOIN tipo_incidente ti ON descripcion = INCIDENTE_BANDERA
		GROUP BY CODIGO_SECTOR,CIRCUITO_CODIGO, CODIGO_CARRERA, INCIDENTE_TIEMPO,ti.id_tipo_incidente
    END
GO

-- Incidente por auto
CREATE PROCEDURE migrar_incidente_por_auto
AS
    BEGIN
        INSERT INTO incidente_por_auto
        (vehiculo_numero,numero_vuelta)
        SELECT AUTO_NUMERO,INCIDENTE_NUMERO_VUELTA
        FROM GD1C2022.gd_esquema.maestra
		WHERE AUTO_NUMERO IS NOT NULL
		GROUP BY AUTO_NUMERO, INCIDENTE_NUMERO_VUELTA
    END
GO
-- Vehiculo
CREATE PROCEDURE migrar_vehiculo
AS
BEGIN
        INSERT INTO vehiculo
        (vehiculo_numero,vehiculo_modelo)
        SELECT AUTO_NUMERO, AUTO_MODELO
        FROM GD1C2022.gd_esquema.maestra
		WHERE AUTO_NUMERO IS NOT NULL
		GROUP BY AUTO_NUMERO, AUTO_MODELO
END

GO
-- Neumatico
CREATE PROCEDURE migrar_neumatico --//TODO CHECK
AS
    BEGIN
        INSERT INTO neumatico
        (neumatico_nro_serie,id_tipo_neumatico)
        SELECT NEUMATICO1_NRO_SERIE_VIEJO,NEUMATICO1_TIPO_VIEJO
        FROM GD1C2022.gd_esquema.maestra
		WHERE NEUMATICO1_NRO_SERIE_VIEJO IS NOT NULL
        UNION
        SELECT NEUMATICO2_NRO_SERIE_VIEJO,NEUMATICO2_TIPO_VIEJO
        FROM GD1C2022.gd_esquema.maestra
		WHERE NEUMATICO2_NRO_SERIE_VIEJO IS NOT NULL
        UNION
        SELECT NEUMATICO3_NRO_SERIE_VIEJO,NEUMATICO3_TIPO_VIEJO
        FROM GD1C2022.gd_esquema.maestra
		WHERE NEUMATICO3_NRO_SERIE_VIEJO IS NOT NULL
        UNION
        SELECT NEUMATICO4_NRO_SERIE_VIEJO,NEUMATICO4_TIPO_VIEJO
        FROM GD1C2022.gd_esquema.maestra
		WHERE NEUMATICO4_NRO_SERIE_VIEJO IS NOT NULL
        UNION
        SELECT NEUMATICO1_NRO_SERIE_NUEVO,NEUMATICO1_TIPO_NUEVO
        FROM GD1C2022.gd_esquema.maestra
		WHERE NEUMATICO1_NRO_SERIE_NUEVO IS NOT NULL
        UNION
        SELECT NEUMATICO2_NRO_SERIE_NUEVO,NEUMATICO2_TIPO_NUEVO
        FROM GD1C2022.gd_esquema.maestra
		WHERE NEUMATICO2_NRO_SERIE_NUEVO IS NOT NULL
        UNION
        SELECT NEUMATICO3_NRO_SERIE_NUEVO,NEUMATICO3_TIPO_NUEVO
        FROM GD1C2022.gd_esquema.maestra
		WHERE NEUMATICO3_NRO_SERIE_NUEVO IS NOT NULL
        UNION
        SELECT NEUMATICO4_NRO_SERIE_NUEVO,NEUMATICO4_TIPO_NUEVO
        FROM GD1C2022.gd_esquema.maestra
		WHERE NEUMATICO4_NRO_SERIE_NUEVO IS NOT NULL
END


GO
--Parada box por vehiculo
CREATE PROCEDURE migrar_parada_box_por_vehiculo
AS
BEGIN
	INSERT INTO parada_box_por_vehiculo
	(vehiculo_numero,nro_serie_neumatico_viejo,nro_serie_neumatico_nuevo)
	SELECT AUTO_NUMERO,NEUMATICO1_NRO_SERIE_VIEJO,NEUMATICO1_NRO_SERIE_NUEVO 
	FROM GD1C2022.gd_esquema.Maestra
	WHERE AUTO_NUMERO IS NOT NULL
	UNION
    SELECT AUTO_NUMERO,NEUMATICO2_NRO_SERIE_VIEJO,NEUMATICO2_TIPO_NUEVO
    FROM GD1C2022.gd_esquema.maestra
	WHERE AUTO_NUMERO IS NOT NULL
    UNION
    SELECT AUTO_NUMERO,NEUMATICO3_NRO_SERIE_VIEJO,NEUMATICO3_TIPO_NUEVO
    FROM GD1C2022.gd_esquema.maestra
	WHERE AUTO_NUMERO IS NOT NULL
    UNION
    SELECT AUTO_NUMERO,NEUMATICO4_NRO_SERIE_VIEJO,NEUMATICO4_TIPO_NUEVO
    FROM GD1C2022.gd_esquema.maestra
	WHERE AUTO_NUMERO IS NOT NULL
END 


/*
CREATE PROCEDURE migrar_tipo_neumatico 
AS
BEGIN
INSERT INTO tipo_neumatico
select TIPO TIPO NEUMATICO
from gd_esquema.Maestra
END
GO
*/
-- Caja
-- Motor
-- Freno
-- Tipo neumatico
-- Tipo Sector
-- Tipo incidente
-- Pais 
-- Bandera
-- Escuderia
-- Piloto
-- Carrera
-- Sector
-- Parada box
-- Telemetria caja
-- Telemetria motor
-- Telemetria neumatico
-- Telemetria freno
-- Telemetria auto
-- Circuito
-- Indicente
-- Incidente por auto
-- Vehiculo
-- Parada box por auto
-- Neumatico


----------------------------
/*

*/