USE [GD1C2022]
GO

CREATE PROCEDURE [GRUPO_9800].CREATE_BI_TABLES
AS
BEGIN
    IF NOT EXISTS(SELECT [name] FROM sys.tables WHERE [name] = '[GRUPO_9800].BI_PARADAS')
    BEGIN
        CREATE TABLE GRUPO_9800.BI_CIRCUITO (
            ID_BI_CIRCUITO INT IDENTITY PRIMARY KEY,
            TIPO_SECTOR INT REFERENCES TIPO_SECTOR,
            TELE_AUTO_COD INT REFERENCES GRUPO_9800.TELEMETRIA_AUTO,
            NEUMATICO_NRO_SERIE NVARCHAR(255),
            FRENO_NRO_SERIE NVARCHAR(255),
            CAJA_NRO_SERIE NVARCHAR(255),
            MOTOR_NRO_SERIE NVARCHAR(255),
            DESGASTE_NUEVO_NEUMATICO DECIMAL(18,6),
            DESGASTE_VIEJO_NEUMATICO DECIMAL(18,6),
            DESGASTE_NUEVO_FRENO DECIMAL(18,2),
            DESGASTE_VIEJO_FRENO DECIMAL(18,2),
            POTENCIA_VIEJA_MOTOR NUMERIC(18,6),
            POTENCIA_NUEVA_MOTOR NUMERIC(18,6),
            DESGASTE_VIEJO_CAJA NUMERIC(18,2),
            DESGASTE_NUEVO_CAJA NUMERIC(18,2),
            VEHICULO INT,
            COD_ESCUDERIA INT,
            NUMERO_VUELTA NUMERIC(18,0),
            CIRCUITO_CODIGO INT,
            TIEMPO_VUELTA NUMERIC(18,10),
            COMBUSTIBLE_CONSUMIDO DECIMAL(18,2),
            VELOCIDAD DECIMAL(18,2),
            SECTOR INT
        );

        ALTER TABLE GRUPO_9800.BI_CIRCUITO
		ADD CONSTRAINT FK_BICircuito_Neumatico
		FOREIGN KEY(TELE_AUTO_COD, NEUMATICO_NRO_SERIE) REFERENCES GRUPO_9800.TELEMETRIA_NEUMATICO(TELE_AUTO_COD, NEUMATICO_NRO_SERIE);

        ALTER TABLE GRUPO_9800.BI_CIRCUITO
		ADD CONSTRAINT FK_BICircuito_Freno
		FOREIGN KEY(TELE_AUTO_COD, FRENO_NRO_SERIE ) REFERENCES GRUPO_9800.TELEMETRIA_FRENO(TELE_AUTO_COD, FRENO_NRO_SERIE );

        ALTER TABLE GRUPO_9800.BI_CIRCUITO
		ADD CONSTRAINT FK_BICircuito_Caja
		FOREIGN KEY(TELE_AUTO_COD, CAJA_NRO_SERIE) REFERENCES GRUPO_9800.TELEMETRIA_CAJA(TELE_AUTO_COD, CAJA_NRO_SERIE);

        ALTER TABLE GRUPO_9800.BI_CIRCUITO
		ADD CONSTRAINT FK_BICircuito_Motor
		FOREIGN KEY(TELE_AUTO_COD, MOTOR_NRO_SERIE) REFERENCES GRUPO_9800.TELEMETRIA_MOTOR(TELE_AUTO_COD, MOTOR_NRO_SERIE);
    END


    IF NOT EXISTS(SELECT [name] FROM sys.tables WHERE [name] = '[GRUPO_9800].BI_PARADAS')
        CREATE TABLE GRUPO_9800.BI_PARADAS (
            ID_BI_CIRCUITO INT IDENTITY PRIMARY KEY,
            COD_ESCUDERIA INT REFERENCES GRUPO_9800.ESCUDERIA,
            CIRCUITO_CODIGO INT REFERENCES GRUPO_9800.CIRCUITO,
            COD_PARADA_BOX INT REFERENCES GRUPO_9800.PARADA_BOX,
            TIEMPO_PARADA_BOX NUMERIC(18,2)
        );


    IF NOT EXISTS(SELECT [name] FROM sys.tables WHERE [name] = '[GRUPO_9800].BI_INCIDENTE')
        CREATE TABLE GRUPO_9800.BI_INCIDENTE (
            ID_BI_INCIDENTE INT IDENTITY PRIMARY KEY,
            COD_INCIDENTE INT REFERENCES GRUPO_9800.INCIDENTE,
            ID_TIPO_SECTOR INT REFERENCES GRUPO_9800.TIPO_SECTOR,
            COD_ESCUDERIA INT REFERENCES GRUPO_9800.ESCUDERIA,
            CIRCUITO_CODIGO INT REFERENCES GRUPO_9800.CIRCUITO
        );
END
GO