------------------- DROP DE TABLAS -------------------
DROP TABLE TELEMETRIA_CARRERA.TELEMETRIA_CARRERA.carrera;
DROP TABLE TELEMETRIA_CARRERA.circuito;
DROP TABLE TELEMETRIA_CARRERA.sector;
DROP TABLE TELEMETRIA_CARRERA.incidente;
DROP TABLE TELEMETRIA_CARRERA.auto;
DROP TABLE TELEMETRIA_CARRERA.escuderia;
DROP TABLE TELEMETRIA_CARRERA.piloto;
DROP TABLE TELEMETRIA_CARRERA.parada_box;
DROP TABLE TELEMETRIA_CARRERA.neumatico;
DROP TABLE TELEMETRIA_CARRERA.telemetria_auto;
DROP TABLE TELEMETRIA_CARRERA.telemetria_motor;
DROP TABLE TELEMETRIA_CARRERA.telemetria__neumatico;
DROP TABLE TELEMETRIA_CARRERA.telemetria_freno;
DROP TABLE TELEMETRIA_CARRERA.telemetria_caja;
DROP TABLE TELEMETRIA_CARRERA.caja;
DROP TABLE TELEMETRIA_CARRERA.motor;
DROP TABLE TELEMETRIA_CARRERA.freno;
DROP TABLE TELEMETRIA_CARRERA.incidente_por_auto;
DROP TABLE TELEMETRIA_CARRERA.parada_box_por_auto;
DROP TABLE TELEMETRIA_CARRERA.tipo_neumatico;
DROP TABLE TELEMETRIA_CARRERA.tipo_sector;
DROP TABLE TELEMETRIA_CARRERA.tipo_incidente;
DROP TABLE TELEMETRIA_CARRERA.pais;
DROP TABLE TELEMETRIA_CARRERA.bandera;

------------------- DROP DE PROCEDURES -------------------
-- Los procedurales de los inserts
-- DROP PROCEDURE migrar_....

------------------- DROP DE VISTAS -------------------
-- DROP VIEW TELEMETRIA_CARRERA.nobre_vista;

------------------- DROP DE INDICES -------------------
-- DROP INDEX TELEMETRIA_CARRERA.tabla.index_name;